### ISSUE TITLE
Error https related to netty version

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/spark-jobs#16]
Spark and Play WS use a different version of netty that change in the method signature for dealing with https requests. It looks like that spark requires netty 3.8.0.Final while play requires 3.10.0.Final where the constructor of the class `org.jboss.netty.handler.ssl.SslHandler` is changed on the signature

``` bash
aused by: java.lang.NoSuchMethodError: org.jboss.netty.handler.ssl.SslHandler.<init>(Ljavax/net/ssl/SSLEngine;Lorg/jboss/netty/handler/ssl/SslBufferPool;ZLorg/jboss/netty/util/Timer;J)V
    at com.ning.http.client.providers.netty.channel.ChannelManager.createSslHandler(ChannelManager.java:400)
    at com.ning.http.client.providers.netty.channel.SslInitializer.connectRequested(SslInitializer.java:44)
    at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
    at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
    at org.jboss.netty.channel.Channels.connect(Channels.java:634)
    at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
    at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
    at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
    at com.ning.http.client.providers.netty.request.NettyRequestSender.connect(NettyRequestSender.java:378)
    at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:282)
    ... 30 more
```

**Comment by fabiofumarola** [comment]
work around I switched all the https connections to http

**Comment by tmcgrath** [comment]
I ran into the same thing and ended up using the "spark.driver.userClassPathFirst" conf variable.  It's been working fine so far.  Documented under "Challenge 2" on this page [https://www.supergloo.com/fieldnotes/apache-spark-advanced-cluster-deploy-scenarios/]
