### ISSUE TITLE
Kafka Error Avro

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/spark-jobs#18]
``` bash
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serialization.ByteArrayDeserializer for configuration value.deserializer: Class org.apache.kafka.common.serialization.ByteArrayDeserializer could not be found.
    at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:255)
    at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:145)
    at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:49)
    at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
    at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:336)
    at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:512)
    at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:494)
    at it.dtk.streaming.receivers.avro.KafkaArticleActorAvro.<init>(KafkaArticleActorAvro.scala:25)
```

**Comment by xishao** [comment]
hi ,do you have the answer?
